/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import { Inter, Nanum_Gothic_Coding } from '@next/font/google'
import styles from './Home.module.css'

const inter = Inter({ subsets: ['latin'] })
const inter_light = Inter({subsets:['latin'], weight:"300"})
const Code = Nanum_Gothic_Coding({ subsets: ['latin'], weight: "400" })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={inter.style} id={styles.frame}>
        <div>
          <h1>I'm <span id={styles.name}>Nahuel Rabey</span></h1>
          <p style={Code.style} id={styles.kind}>{"<Software Developer/>"}</p>
        </div>

        <div style={inter_light.style} id={styles.desc}>
          <p>
            I am a multi-talented software developer with expertise in web and desktop applications, front-end and back-end technologies, microservices architecture, and Linux configurations.
          </p>

          <p>
            As a data science student, I am constantly learning and growing my skills in machine learning and data analysis. I am eager to apply these skills to real-world problems and make a positive impact through my work.
          </p>
        </div>
      </main>
    </>
  )
}
